os:
  - linux
  - osx
language: node_js
node_js:
  - 'stable'
  - '9'
  - '8'
  - '7'
  - '6'
after_script:
  - yarn global add codeclimate-test-reporter codecov codacy-coverage coveralls
  - codeclimate-test-reporter < coverage/lcov.info
  - codecov -f coverage/lcov.info
  - cat ./coverage/lcov.info | codacy-coverage
  - cat ./coverage/lcov.info | coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache: yarn
