language: node_js
node_js:
  - "stable"
  - "7"
  - "6"
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm install -g codecov
  - codecov -f coverage/lcov.info
