# Test against the latest version of this Node.js version
environment:
  matrix:
    - node_version: "8"
    - node_version: "7"
    - node_version: "6"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:node_version
  - yarn install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm test

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

# Don't actually build.
build: off
