workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v6
      - node-v7
      - node-v8
      - node-v9
      - node-v10

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Test
          command: npm test
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  node-v6:
    <<: *node-base
    docker:
      - image: node:6
  node-v7:
    <<: *node-base
    docker:
      - image: node:7
  node-v8:
    <<: *node-base
    docker:
      - image: node:8
  node-v9:
    <<: *node-base
    docker:
      - image: node:9
  node-v10:
    <<: *node-base
    docker:
      - image: node:10
